### ISSUE TITLE
Add class support to d34r `selection.(select|selectAll)`

### ISSUE THREAD

**Issue by webmonarch** [webmonarch/d34raphael#2] opened 2012-05-03 03:26 UTC
Current, when calling selection.select(selector), the selector is only allowed to be a primitive element name (ie: circle, rect, path).  

the selector capability should be expanded to support selecting on node class name, ie:

`selection.selectAll("circle.point")`

**Comment by issa-tseng** [comment] 2012-05-31 18:08
As far as I'm aware Raphael doesn't support classes at all natively; would the solution be to drill through to the elem.node?

PS the documentation currently uses .attr('class','point') despite it not working.

**Comment by issa-tseng** [comment] 2012-05-31 18:19
Never mind, the issue is that the .attr({ ... }) syntax doesn't support class.

**Comment by issa-tseng** [comment] 2012-06-01 03:01
Downside of this split repository approach is that I can't directly attach a pull request to this issue. See here instead:
https://github.com/webmonarch/d3/pull/1

**Comment by webmonarch** [comment] 2012-06-01 05:59
@clint-tseng Thanks.  I've updated the issue description to more clearly explain my intent.  

RE: the `selection.attr({attrName: attrVal})` syntax: right now, d34r selection.attr call follows the API set by d3.  The .attr({name: val, name: val}) syntax is part of Raphael Element.attr call.

Let me know if I miss-understood.  I will take a look at the pull-request.

**Comment by issa-tseng** [comment] 2012-06-01 06:05
RE: the {} syntax, I think it's important to be consistent, so the API should either accept { class: '...' }, or we should make .attr('class', '...') throw not supported and force people to use .classed(...) instead. I think aesthetically the latter mirrors Raphael better, but the former certainly eases transitional issues from standard D3.

**Comment by webmonarch** [comment] 2012-06-01 06:20
@clint-tseng I expect selection.attr("class", "classname") to work on d34r.  It's used in all the examples.

**Comment by issa-tseng** [comment] 2012-06-01 06:30
Yes, and it does. But, selection.attr({ class: 'className' }) does not. The inconsistency there is somewhat confusing in my mind.

**Comment by mhemesath** [comment] 2012-06-05 03:44
I agree with webmonarch. You can't use class because it's a reserved word and the browser will tell you so, it's not an inconsistency.

**Comment by issa-tseng** [comment] 2012-06-05 03:48
But that's not why it doesn't work, right? I could easily (and I do) use { 'class': 'className' }. It works in D3. I think it's confusing that it doesn't work in D34r. I'm not trying to make any religious argument here, I'm just trying to point out an inconsistency in the API that cost me a couple of hours.

**Comment by mhemesath** [comment] 2012-06-05 03:58
It is not an inconsistency with the API, it is a consistency with JavaScript.  class is not the same as "class".  For this same reason class name properties are assigned to elements via className instead of class.  class is a reserved word.

**Comment by issa-tseng** [comment] 2012-06-05 04:05
Hrm. I see what you're saying. On the other hand, I could swear that last week I was using { 'class': 'className' } in raw d3 and it was working fine. If it's well-known that one should use { className: 'className' } then I defer to that.

I still think it's odd that we allow .attr('class', 'className') if the .attr({'class', 'className'}) version isn't supported, though.

**Comment by mhemesath** [comment] 2012-06-05 04:22
className is not a raphael or D3 convention, its what the DOM uses to assign class names to elements.   

As far as .attr('class', 'className') goes, the goal of d34raphael is to make an IE compatible version of D3 that resembles the original D3 as close as possible.  The fact that Raphael is used as a compatibility layer for a SVG fallback should be exposed as little as possible.

**Comment by issa-tseng** [comment] 2013-12-27 19:34
Resolved between https://github.com/webmonarch/d3/pull/1 and https://github.com/webmonarch/d3/commit/c6ac75c0f00090b905dd68f254d389edbca0e1f0

**Closed as completed by issa-tseng** 2013-12-27 19:34 UTC
Labels: enhancement
